name: cg-lab6
channels:
  - pytorch3d
  - pytorch
  - nvidia
  - iopath
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.1
  - pytorch3d
  - iopath
  - matplotlib
  - imageio
  - pip
